# Generated by Django 6.0.1 on 2026-03-05 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marche_smart', '0006_alter_cartitem_added_at_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLForecastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('model_type', models.CharField(choices=[('arima', 'ARIMA Time Series'), ('lstm', 'LSTM Neural Network'), ('prophet', 'Facebook Prophet'), ('regression', 'Linear Regression'), ('random_forest', 'Random Forest'), ('xgboost', 'XGBoost'), ('ensemble', 'Ensemble Model')], max_length=20)),
                ('forecast_type', models.CharField(choices=[('demand', 'Demand Forecasting'), ('revenue', 'Revenue Forecasting'), ('inventory', 'Inventory Optimization'), ('pricing', 'Price Optimization'), ('seasonal', 'Seasonal Analysis')], max_length=20)),
                ('parameters', models.JSONField(default=dict, help_text='Model hyperparameters')),
                ('features_used', models.JSONField(default=list, help_text='List of features used in the model')),
                ('accuracy_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('mae', models.DecimalField(decimal_places=2, default=0, help_text='Mean Absolute Error', max_digits=10)),
                ('rmse', models.DecimalField(decimal_places=2, default=0, help_text='Root Mean Square Error', max_digits=10)),
                ('mape', models.DecimalField(decimal_places=2, default=0, help_text='Mean Absolute Percentage Error', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('last_trained', models.DateTimeField(blank=True, null=True)),
                ('next_retrain_date', models.DateTimeField(blank=True, null=True)),
                ('model_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-accuracy_score', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='avg_monthly_sales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average monthly sales for forecasting', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='avg_weekly_sales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average weekly sales for forecasting', max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='demand_trend',
            field=models.CharField(choices=[('increasing', 'Increasing'), ('decreasing', 'Decreasing'), ('stable', 'Stable'), ('volatile', 'Volatile'), ('seasonal', 'Seasonal Pattern')], default='stable', help_text='Overall demand trend for ML forecasting', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='economic_sensitive',
            field=models.BooleanField(default=False, help_text='Sales sensitive to economic conditions'),
        ),
        migrations.AddField(
            model_name='product',
            name='festival_association',
            field=models.CharField(choices=[('diwali', 'Diwali'), ('holi', 'Holi'), ('eid', 'Eid'), ('christmas', 'Christmas'), ('new_year', 'New Year'), ('durga_puja', 'Durga Puja'), ('ganesh_chaturthi', 'Ganesh Chaturthi'), ('karwa_chauth', 'Karwa Chauth'), ('dussehra', 'Dussehra'), ('raksha_bandhan', 'Raksha Bandhan'), ('valentine', "Valentine's Day"), ('mother_day', "Mother's Day"), ('father_day', "Father's Day"), ('none', 'No Festival Association')], default='none', help_text='Festival period when this product is in high demand', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='festival_sales_boost',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Sales multiplier during associated festival period', max_digits=3),
        ),
        migrations.AddField(
            model_name='product',
            name='forecast_accuracy',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ML model accuracy percentage (0-100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='last_forecast_update',
            field=models.DateTimeField(blank=True, help_text='Last time ML predictions were updated', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lead_time_days',
            field=models.IntegerField(default=7, help_text='Lead time for restocking (days)'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_stock_level',
            field=models.IntegerField(default=1000, help_text='Maximum stock capacity'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock_level',
            field=models.IntegerField(default=0, help_text='Minimum stock level for alerts'),
        ),
        migrations.AddField(
            model_name='product',
            name='monthly_sales_pattern',
            field=models.JSONField(blank=True, default=dict, help_text='Sales pattern by month {1: 120, 2: 85, ...} representing relative sales'),
        ),
        migrations.AddField(
            model_name='product',
            name='peak_season',
            field=models.CharField(choices=[('spring', 'Spring (March-May)'), ('summer', 'Summer (June-August)'), ('monsoon', 'Monsoon (September-November)'), ('winter', 'Winter (December-February)'), ('all_year', 'All Year Round')], default='all_year', help_text='Primary season when this product sells most', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='predicted_demand_30d',
            field=models.IntegerField(default=0, help_text='ML predicted demand for next 30 days'),
        ),
        migrations.AddField(
            model_name='product',
            name='predicted_demand_7d',
            field=models.IntegerField(default=0, help_text='ML predicted demand for next 7 days'),
        ),
        migrations.AddField(
            model_name='product',
            name='predicted_revenue_30d',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ML predicted revenue for next 30 days', max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='price_elasticity',
            field=models.DecimalField(decimal_places=3, default=1.0, help_text='Price elasticity coefficient for ML models', max_digits=4),
        ),
        migrations.AddField(
            model_name='product',
            name='promotion_lift',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Average sales lift during promotions', max_digits=4),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_point',
            field=models.IntegerField(default=0, help_text='Automatic reorder point'),
        ),
        migrations.AddField(
            model_name='product',
            name='seasonal_coefficients',
            field=models.JSONField(blank=True, default=dict, help_text='Seasonal multipliers by month/week for ML models'),
        ),
        migrations.AddField(
            model_name='product',
            name='seasonal_priority',
            field=models.IntegerField(default=1, help_text='Priority for seasonal recommendations (1-10, higher = more priority)'),
        ),
        migrations.AddField(
            model_name='product',
            name='stockout_frequency',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Stock-out frequency (times per year)', max_digits=4),
        ),
        migrations.AddField(
            model_name='product',
            name='weather_dependent',
            field=models.BooleanField(default=False, help_text='Sales affected by weather patterns'),
        ),
        migrations.AddField(
            model_name='product',
            name='weekend_boost',
            field=models.BooleanField(default=False, help_text='Product sells significantly more on weekends'),
        ),
        migrations.AddField(
            model_name='product',
            name='weekend_sales_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Weekend sales multiplier (e.g., 1.5 = 50% more sales)', max_digits=3),
        ),
        migrations.AddField(
            model_name='smartproducts',
            name='avg_monthly_sales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average monthly sales for forecasting', max_digits=10),
        ),
        migrations.AddField(
            model_name='smartproducts',
            name='avg_weekly_sales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average weekly sales for forecasting', max_digits=8),
        ),
        migrations.AddField(
            model_name='smartproducts',
            name='demand_trend',
            field=models.CharField(choices=[('increasing', 'Increasing'), ('decreasing', 'Decreasing'), ('stable', 'Stable'), ('volatile', 'Volatile'), ('seasonal', 'Seasonal Pattern')], default='stable', help_text='Overall demand trend for ML forecasting', max_length=20),
        ),
        migrations.AddField(
            model_name='smartproducts',
            name='economic_sensitive',
            field=models.BooleanField(default=False, help_text='Sales sensitive to economic conditions'),
        ),
        migrations.AddField(
            model_name='smartproducts',
            name='festival_association',
            field=models.CharField(choices=[('diwali', 'Diwali'), ('holi', 'Holi'), ('eid', 'Eid'), ('christmas', 'Christmas'), ('new_year', 'New Year'), ('durga_puja', 'Durga Puja'), ('ganesh_chaturthi', 'Ganesh Chaturthi'), ('karwa_chauth', 'Karwa Chauth'), ('dussehra', 'Dussehra'), ('raksha_bandhan', 'Raksha Bandhan'), ('valentine', "Valentine's Day"), ('mother_day', "Mother's Day"), ('father_day', "Father's Day"), ('none', 'No Festival Association')], default='none', help_text='Festival period when this product is in high demand', max_length=20),
        ),
        migrations.AddField(
            model_name='smartproducts',
            name='festival_sales_boost',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Sales multiplier during associated festival period', max_digits=3),
        ),
        migrations.AddField(
            model_name='smartproducts',
            name='forecast_accuracy',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ML model accuracy percentage (0-100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='smartproducts',
            name='last_forecast_update',
            field=models.DateTimeField(blank=True, help_text='Last time ML predictions were updated', null=True),
        ),
        migrations.AddField(
            model_name='smartproducts',
            name='lead_time_days',
            field=models.IntegerField(default=7, help_text='Lead time for restocking (days)'),
        ),
        migrations.AddField(
            model_name='smartproducts',
            name='max_stock_level',
            field=models.IntegerField(default=1000, help_text='Maximum stock capacity'),
        ),
        migrations.AddField(
            model_name='smartproducts',
            name='min_stock_level',
            field=models.IntegerField(default=0, help_text='Minimum stock level for alerts'),
        ),
        migrations.AddField(
            model_name='smartproducts',
            name='monthly_sales_pattern',
            field=models.JSONField(blank=True, default=dict, help_text='Sales pattern by month {1: 120, 2: 85, ...} representing relative sales'),
        ),
        migrations.AddField(
            model_name='smartproducts',
            name='peak_season',
            field=models.CharField(choices=[('spring', 'Spring (March-May)'), ('summer', 'Summer (June-August)'), ('monsoon', 'Monsoon (September-November)'), ('winter', 'Winter (December-February)'), ('all_year', 'All Year Round')], default='all_year', help_text='Primary season when this product sells most', max_length=20),
        ),
        migrations.AddField(
            model_name='smartproducts',
            name='predicted_demand_30d',
            field=models.IntegerField(default=0, help_text='ML predicted demand for next 30 days'),
        ),
        migrations.AddField(
            model_name='smartproducts',
            name='predicted_demand_7d',
            field=models.IntegerField(default=0, help_text='ML predicted demand for next 7 days'),
        ),
        migrations.AddField(
            model_name='smartproducts',
            name='predicted_revenue_30d',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ML predicted revenue for next 30 days', max_digits=12),
        ),
        migrations.AddField(
            model_name='smartproducts',
            name='price_elasticity',
            field=models.DecimalField(decimal_places=3, default=1.0, help_text='Price elasticity coefficient for ML models', max_digits=4),
        ),
        migrations.AddField(
            model_name='smartproducts',
            name='promotion_lift',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Average sales lift during promotions', max_digits=4),
        ),
        migrations.AddField(
            model_name='smartproducts',
            name='reorder_point',
            field=models.IntegerField(default=0, help_text='Automatic reorder point'),
        ),
        migrations.AddField(
            model_name='smartproducts',
            name='seasonal_coefficients',
            field=models.JSONField(blank=True, default=dict, help_text='Seasonal multipliers by month/week for ML models'),
        ),
        migrations.AddField(
            model_name='smartproducts',
            name='seasonal_priority',
            field=models.IntegerField(default=1, help_text='Priority for seasonal recommendations (1-10, higher = more priority)'),
        ),
        migrations.AddField(
            model_name='smartproducts',
            name='stockout_frequency',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Stock-out frequency (times per year)', max_digits=4),
        ),
        migrations.AddField(
            model_name='smartproducts',
            name='weather_dependent',
            field=models.BooleanField(default=False, help_text='Sales affected by weather patterns'),
        ),
        migrations.AddField(
            model_name='smartproducts',
            name='weekend_boost',
            field=models.BooleanField(default=False, help_text='Product sells significantly more on weekends'),
        ),
        migrations.AddField(
            model_name='smartproducts',
            name='weekend_sales_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Weekend sales multiplier (e.g., 1.5 = 50% more sales)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductRecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('seasonal', 'Seasonal Recommendation'), ('festival', 'Festival Recommendation'), ('weekend', 'Weekend Favorite'), ('trending', 'Trending Product')], max_length=30)),
                ('context_data', models.JSONField(default=dict, help_text='Context like season, festival, etc.')),
                ('was_viewed', models.BooleanField(default=False)),
                ('was_added_to_cart', models.BooleanField(default=False)),
                ('was_purchased', models.BooleanField(default=False)),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marche_smart.product')),
                ('smart_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marche_smart.smartproducts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recommended_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(default='Store Location', max_length=100)),
                ('temperature_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rainfall', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('condition', models.CharField(blank=True, choices=[('sunny', 'Sunny'), ('rainy', 'Rainy'), ('cloudy', 'Cloudy'), ('stormy', 'Stormy'), ('snowy', 'Snowy'), ('hot', 'Hot'), ('cold', 'Cold'), ('humid', 'Humid')], max_length=20)),
                ('sales_impact_score', models.DecimalField(decimal_places=2, default=1.0, help_text='Sales multiplier based on weather', max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'location')},
            },
        ),
        migrations.CreateModel(
            name='ForecastPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('target_date', models.DateTimeField(help_text='Date this prediction is for')),
                ('horizon', models.CharField(choices=[('1d', '1 Day'), ('7d', '7 Days'), ('30d', '30 Days'), ('90d', '90 Days'), ('1y', '1 Year')], max_length=10)),
                ('predicted_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confidence_interval_lower', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confidence_interval_upper', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prediction_error', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_accurate', models.BooleanField(blank=True, help_text='Within confidence interval', null=True)),
                ('context_data', models.JSONField(default=dict, help_text='Additional context for this prediction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marche_smart.product')),
                ('smart_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marche_smart.smartproducts')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='marche_smart.mlforecastmodel')),
            ],
            options={
                'ordering': ['-prediction_date'],
                'unique_together': {('model', 'product', 'target_date'), ('model', 'smart_product', 'target_date')},
            },
        ),
        migrations.CreateModel(
            name='SeasonalSalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('week_of_year', models.IntegerField()),
                ('is_weekend', models.BooleanField(default=False)),
                ('is_festival_period', models.BooleanField(default=False)),
                ('festival_name', models.CharField(blank=True, max_length=50, null=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('units_sold', models.IntegerField(default=0)),
                ('average_daily_sales', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('season', models.CharField(blank=True, max_length=20)),
                ('performance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_sales', to='marche_smart.product')),
                ('smart_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_sales', to='marche_smart.smartproducts')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('product', 'year', 'month'), ('smart_product', 'year', 'month')},
            },
        ),
    ]
