# Generated by Django 6.0.1 on 2026-03-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marche_smart', '0007_mlforecastmodel_product_avg_monthly_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_order', 'New Order'), ('order_cancelled', 'Order Cancelled'), ('payment_received', 'Payment Received'), ('low_stock', 'Low Stock Alert'), ('new_customer', 'New Customer Registration'), ('support_ticket', 'Support Ticket'), ('system', 'System Notification')], max_length=20),
        ),
    ]
