# Generated by Django 6.0.1 on 2026-03-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marche_smart', '0008_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='festival_association',
            field=models.CharField(choices=[('diwali', 'Diwali'), ('holi', 'Holi'), ('eid', 'Eid'), ('christmas', 'Christmas'), ('easter', 'Easter'), ('new_year', 'New Year'), ('durga_puja', 'Durga Puja'), ('ganesh_chaturthi', 'Ganesh Chaturthi'), ('karwa_chauth', 'Karwa Chauth'), ('dussehra', 'Dussehra'), ('raksha_bandhan', 'Raksha Bandhan'), ('valentine', "Valentine's Day"), ('mother_day', "Mother's Day"), ('father_day', "Father's Day"), ('none', 'No Festival Association')], default='none', help_text='Festival period when this product is in high demand', max_length=20),
        ),
        migrations.AlterField(
            model_name='smartproducts',
            name='festival_association',
            field=models.CharField(choices=[('diwali', 'Diwali'), ('holi', 'Holi'), ('eid', 'Eid'), ('christmas', 'Christmas'), ('easter', 'Easter'), ('new_year', 'New Year'), ('durga_puja', 'Durga Puja'), ('ganesh_chaturthi', 'Ganesh Chaturthi'), ('karwa_chauth', 'Karwa Chauth'), ('dussehra', 'Dussehra'), ('raksha_bandhan', 'Raksha Bandhan'), ('valentine', "Valentine's Day"), ('mother_day', "Mother's Day"), ('father_day', "Father's Day"), ('none', 'No Festival Association')], default='none', help_text='Festival period when this product is in high demand', max_length=20),
        ),
    ]
