# Generated by Django 6.0.1 on 2026-03-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marche_smart', '0009_alter_product_festival_association_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('home_delivery', 'Home Delivery'), ('store_pickup', 'Store Pickup')], default='home_delivery', help_text='Whether order is for home delivery or store pickup', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_store',
            field=models.CharField(blank=True, help_text='Store location if store pickup is selected', max_length=50, null=True),
        ),
    ]
